### ISSUE TITLE
NK FIDO2: doc pages for Linux and macOS could be unified

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#11]
Documentation pages for Linux and macOS could be merged to a single page, briefly looking how similar content is.
Similarly for Windows as far as I see. Perhaps some refactoring could be used?

- https://github.com/Nitrokey/nitrokey-documentation/tree/master/fido2/linux
- https://github.com/Nitrokey/nitrokey-documentation/tree/master/fido2/windows
- https://github.com/Nitrokey/nitrokey-documentation/tree/master/fido2/mac

**Comment by sbstrkt** [comment]
Ok, I will take a look at this, and build symlinks when it is redundant. Setting up the environment today.

**Comment by jans23** [comment]
The guides are largely identical but not completely. Therefore they are separate.

**Comment by jans23** [comment]
https://github.com/Nitrokey/nitrokey-documentation/pull/48
