### ISSUE TITLE
outdated link

### ISSUE THREAD

**Issue by schaarsc** [Nitrokey/nitrokey-documentation#117]
File: [nitrokey3/linux/desktop-login.rst] https://docs.nitrokey.com/nitrokey3/linux/desktop-login.html

in the section Requirements the link for "[these instructions](https://www.nitrokey.com/documentation/installation#p:nitrokey-fido-u2f&os:linux)." is not working

**Comment by egurn** [comment]
Thank you for the hint! We've updated that with #137.
