### ISSUE TITLE
NitroPC OS Reinstalltion add bios reference and remove heads

### ISSUE THREAD

**Issue by nestire** [Nitrokey/nitrokey-documentation#138]
See Here:
Point 4. Heads reference (should not exist under NitroPC)
https://docs.nitrokey.com/nitropc/qubes/os-reinstallation
https://docs.nitrokey.com/nitropc/ubuntu/os-reinstallation
https://docs.nitrokey.com/nitropc/debian/os-reinstallation

Please add, that you can enter the NitroPC Bios via ESC to USB boot

**Comment by jans23** [comment]
I think this issue is outdated. Today we ship:

- NitroPC 1 with TianCore only
- NitroPC Pro with Dasharo TianoCore and Heads

Because instructions in `/nitropc/` are generic for both models, the documentation should cover both cases too. @Keksmo
