### ISSUE TITLE
FAQ lacks factory reset

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-documentation#140]
[This information](https://www.nitrokey.com/documentation/frequently-asked-questions-faq#how-to-reset-a-nitrokey) is not in the [FAQ of NK Pro](https://docs.nitrokey.com/pro/faq) yet. Perhaps it lacks in other Nitrokey models' FAQ too.

**Comment by daringer** [comment]
Generally there are specific "factory-reset" pages: https://docs.nitrokey.com/pro/linux/factory-reset
But I second the idea to have this in the FAQ, too...

**Comment by jans23** [comment]
Ah, right, I missed that.
