### ISSUE TITLE
Describe reset commands for all applications

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#155]
Describe reset commands for all applications. Right now only FIDO2 is mentioned, but it lacks Opcard and Secrets App.

File: [nitrokey3/linux/reset.rst] https://docs.nitrokey.com/nitrokey3/linux/reset.html

**Comment by NB2455** [comment]
what exactly did u want added?
![reset](https://github.com/Nitrokey/nitrokey-documentation/assets/89620316/71cbcc03-2c52-442d-8e37-889bfa00e8f5)

**Comment by NB2455** [comment]
Hey, so there is no real way of resetting the PIV key on windows. You can however overwrite a blank file to the slot using a command. My next question is where you would like me to put this command. It can either go in the factory reset of windows: https://docs.nitrokey.com/nitrokey3/windows/reset 
or 
the piv smartcard page
https://docs.nitrokey.com/nitrokey3/windows/piv.html?highlight=piv 
where would you like me to put it?

kind regards,

Nick

**Comment by szszszsz** [comment]
It sounds like the reset page would be good choice here, as this is related to clearing the device.
Ideally I would like to have a link from the PIV to factory reset page, so the user would know how to reset it.
