### ISSUE TITLE
Login to local Windows Account using Nitrokey 3

### ISSUE THREAD

**Issue by anotherbridge** [Nitrokey/nitrokey-documentation#205]
So far I couldn't find any way to enable a Windows login with a local account. I tried an authentication using a User certificate but that didn't seem to be possible for a local account. Further, under the sign-in options I could see a security key and the Nitrokey 3 was detected. I could also change the PIN, but it wouldn't let me set it up for a login.

Is it possible to perform a local account login? If so, what is the procedure for that?

**Comment by daringer** [comment]
So far we know there is no way to do this without additional software that integrates the Nitrokey 3 into the Windows login-process. This means as of now there is no way to achieve this for windows. The most standard conformant way would be to use FIDO2 for that, but [as it seems](https://superuser.com/questions/1441343/how-do-i-log-in-to-my-personal-windows-10-using-a-fido2-key) this is not available for standalone windows machines (yet?).

**Comment by jans23** [comment]
It is possible a) with [PIV](https://docs.nitrokey.com/nitrokey3/windows/piv/guides/client_logon_with_active_directory) and on-premise Active Directory resp. EntraID and b) with [FIDO2](https://docs.nitrokey.com/nitrokey3/windows/passwordless-microsoft) and Azure.
