### ISSUE TITLE
Some pages are not properly formatted

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#23]
Some pages are not properly formatted, e.g. they miss the ordered and unordered lists, which changed between the `md` and `rst` formats. Specifically:
- https://docs.nitrokey.com/start/linux/index.html - missing special section format, no whitespace between the phrase and the url, different formats for code blocks;
- https://docs.nitrokey.com/start/linux/openpgp-email-encryption-with-thunderbird.html - missing paragraph, invalid formatting for MD unordered lists;
- https://docs.nitrokey.com/fido2/windows/index.html#touch-button-and-led-behavior - table is too wide;
- https://docs.nitrokey.com/fido2/windows/index.html#older-versions-of-windows-10 - improper format for ordered list;

**Comment by jans23** [comment]
* Table width: This will be addressed with a custom theme.
* Consistent formatting of code blocks will be addressed separately. 

All other findings should have be solved by now.

**Comment by szszszsz** [comment]
Looks like this one is solved. Closing as done.

One of the links got outdated, checked below instead:
- https://docs.nitrokey.com/start/linux/openpgp-thunderbird.html
