### ISSUE TITLE
FIDO2: missing chapters from the main page

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#24]
Chapters from the main page are not shown in the left sidebar menu for Nitrokey FIDO2. These should be listed to allow user to move in the content.

- https://docs.nitrokey.com/fido2/windows/index.html

![image](https://user-images.githubusercontent.com/17005426/105855194-1a1b9a00-5fe8-11eb-86ad-25f293be56d6.png)

**Comment by benks-io** [comment]
there's a ToC now.

**Comment by szszszsz** [comment]
This seems to still occur - see #39

**Comment by szszszsz** [comment]
Ah, I see it right now. The chapters on the main page are not listed in the left menu, but only on the right. This has confused me, as I missed the TOC on the right. For me it might be more visible to duplicate it at the beginning of the page as well, but this might be personal bias. To discuss.
![image](https://user-images.githubusercontent.com/17005426/124455276-a9905a80-dd89-11eb-9233-5f87f8b685c1.png)

**Comment by jans23** [comment]
@szszszsz Can this be closed?

**Comment by szszszsz** [comment]
My main concern is still not corrected, which is that the main page chapters are not visible in the main tree, which would be intuitive for me. If I got confused, then I would expect some users would be as well, hence I would like to keep it open and solve it by either: - technically, by generating additional level of chapters in the main left menu;
- dividing the main page to subdocs, so it would be listed on the left.

**Comment by jans23** [comment]
For larger instructions combining headings into the left menu would be too confusing, I think. See for example [this page](https://docs.nitrokey.com/pro/linux/openvpn-easyrsa.html).

**Comment by szszszsz** [comment]
I see your point. Then I think the Nitrokey FIDO2 main page should be divided to subpages so the mentioned Reset and other descriptions would be directly visible in the tree.

**Comment by jans23** [comment]
I agree. The main page should contain all information which a new user should need to know, but not more. Hence, reset and other details can be moved to a different page.

**Comment by szszszsz** [comment]
Created #40 for further tasks regarding dividing main FIDO2 document to subpages.
Closing this one as done by introducing TOC per document.
