### ISSUE TITLE
nfc.fail doesn't resolve anymore

### ISSUE THREAD

**Issue by i-love-coffee-i-love-tea** [Nitrokey/nitrokey-documentation#243]
File: [nitrokey3/faq.rst] https://docs.nitrokey.com/nitrokey3/faq.html

https://nfc.fail doesn't seem to be available anymore.
I did a quick internet search, but couldn't find any alternative.

```
$ nslookup nfc.fail
nfc.fail: resolve call failed: 'nfc.fail' does not have any RR of the requested type
```

**Comment by jans23** [comment]
Mabe link to https://support.bagtag.com/hc/en-us/articles/4417056455185-Where-to-the-find-NFC-location-per-phone-brand instead.

**Comment by daringer** [comment]
done

> Mabe link to https://support.bagtag.com/hc/en-us/articles/4417056455185-Where-to-the-find-NFC-location-per-phone-brand instead.

done
