### ISSUE TITLE
default linux install instructions on nitrokey website do not work

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nitrokey-documentation#244]
I am trying to follow the instructions for linux at https://docs.nitrokey.com/software/nk-app2/installation_linux .

However, copy pasting the command gives me an error:

```
> flatpak install com.nitrokey.nitrokey-app2
Looking for matches…
error: No remote refs found similar to ‘com.nitrokey.nitrokey-app2’
```

From https://flathub.org/apps/com.nitrokey.nitrokey-app2 it looks like it should be

```
flatpak install flathub com.nitrokey.nitrokey-app2
```

instead, is this correct? :)

**Comment by robin-nitrokey** [comment]
Good catch, thanks for the report!
