### ISSUE TITLE
Executable and testable documentation

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#26]
It would be nice to have a documentation system, which verifies itself by executing the actions or statements, tests the outcomes and stores all the outputs for the users for comparison. Such actions could include:
- generating keys on the Nitrokey using GnuPG;
- generating DKEK shares.

Details:
- https://support.nitrokey.com/t/nitrokey-start-basic-file-encryption-and-decryption-with-gpg-on-linux/2901/7

**Comment by jans23** [comment]
This would be a project on its own. Closing as won't fix (in the near future) to keep a better overview.
