### ISSUE TITLE
Doc: latest firmwares page

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#28]
A documentation page collecting latest firmware versions for all products would be nice to have.

Details: https://support.nitrokey.com/t/latest-firmware/2883/2

**Comment by jans23** [comment]
I don't see a point in maintain such page. With just a few click users can identify the latest firmware version for a particular model which should be sufficient for most of them. In addition we may add automatic firmware updates to our tools which make this even easier.

**Comment by szszszsz** [comment]
To rephrase (as the initial description is scarce), the idea here is to keep such firmware list in a single web location, so without installing additional software it would be possible to check the latest firmware versions for all models. I believe this would be handy mostly for the enterprise users, where IT administrator might not keep the a physical device by himself, thus automatic check in software would not work.
As for the edge case, the Nitrokey HSM latest firmware version is hard to find (as it is placed in the shared `nitrokey-pro-firmware` space).

**Comment by jans23** [comment]
Still, I'm against it because the benefit is very little and we have more important aspects to document.
