### ISSUE TITLE
improve upon (software) documentation

### ISSUE THREAD

**Issue by iameru** [Nitrokey/nitrokey-documentation#297]
File: [software/index.rst] https://docs.nitrokey.com/software/index.html

Like [other](https://github.com/Nitrokey/nitrokey-documentation/issues/296) [users](https://github.com/Nitrokey/nitrokey-documentation/issues/219)  ([and this](https://github.com/Nitrokey/nitrokey-documentation/issues/171), [and this](https://github.com/Nitrokey/nitrokey-documentation/issues/120) , and more..) I found a sparse documentation.

in https://docs.nitrokey.com/software/index.html there are 2 rather small entries about `Nitrokey App 2` and `nitropy`.

I would have expected some more details on each and some more information on the usage. for example, in my package manager i find `extra/libnitrokey`, `extra/nitrocli`, `extra/nitrokey-app`, `extra/python-nkdfu`, `extra/python-pynitrokey`. Currently, it looks like I'm on my own on figuring out how to use your product.

edit: I found more info, buried.

**Comment by daringer** [comment]
@iameru we are currently rebuilding the docs backend and have some major changes upcoming afterwards - so I hope the situation will improve
