### ISSUE TITLE
picture of sealed V54

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-documentation#303]
This picture of a sealed V54 should be added here https://docs.nitrokey.com/nitropad/qubes/sealed-hardware  and https://docs.nitrokey.com/nitropad/ubuntu/sealed-hardware

![NitroPad V54 Sealing](https://github.com/user-attachments/assets/4c652006-020d-4bbb-aeb7-1ad3d03ef26f)

**Comment by daringer** [comment]
fixed
