### ISSUE TITLE
NitroPC incorrectly named as NitropadX230

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#31]
While exploring other products, the NitroPC submenu is incorrectly named as NitropadX230. Only after opening this submenu the name changes to NitroPC.

![image](https://user-images.githubusercontent.com/17005426/109629264-f1854380-7b43-11eb-80a6-d9a675646a66.png)

**Comment by jans23** [comment]
This was fixed yesterday. Please reload the page.

**Comment by szszszsz** [comment]
It still shows to me, even in another (clean) browser.

**Comment by jans23** [comment]
This is how it looks for me.

![Bildschirmfoto von 2021-03-02 12-04-04](https://user-images.githubusercontent.com/1450547/109639402-6c079080-7b4f-11eb-851d-1722301b89cc.png)

**Comment by szszszsz** [comment]
That's correct. Now please open some other product's submenu and compare.

**Comment by jans23** [comment]
@benks-io Can you fix this?

**Comment by benks-io** [comment]
Should be fixed. Can you confirm @szszszsz?
Sphinx only regenerates updated content. Here, something must have gone wrong.
If it happens again, I can find out why or let the webroot be cleaned on every commit.

**Comment by szszszsz** [comment]
Confirmed - looks good on my side. Closing as fixed.

Perhaps the menu should be always regenerated? If that is possible of course.

**Comment by benks-io** [comment]
Ok. The build script is set to rewrite *all* files.
