### ISSUE TITLE
*.yaml mentioned do not exist

### ISSUE THREAD

**Issue by jpmens** [Nitrokey/nitrokey-documentation#318]
at https://github.com/Nitrokey/nitrokey-documentation/blob/main/source/components/nethsm/container/production-image.rst

**Comment by jans23** [comment]
This documentation is a bit ahead of time and the mentioned Docker compose files are not published yet. I would leave the documentation as is and ask you to wait until the files are published.

**Comment by jpmens** [comment]
Documenting stuff before the code is even there?! That's pretty rad! 😂
