### ISSUE TITLE
Where is the hardware button

### ISSUE THREAD

**Issue by bitfanatic** [Nitrokey/nitrokey-documentation#33]
File: [nextbox/technical/factory-reset.rst] https://docs.nitrokey.com/nextbox/technical/factory-reset

You need to add where to find the hardware button 

Because there isnt one on the outside

Maybe add a picture that always nice 
Maybe add a arrow write next to the arrow 
What the arrow is pointing to

**Comment by daringer** [comment]
jup, good point, will add, in the meantime: the button is next to the LED pinhole

**Comment by daringer** [comment]
https://docs.nitrokey.com/nextbox/technical/factory-reset.html# was updated

**Comment by loneum** [comment]
(Seems I/one cannot re-open issues. Anyway:)
It took me quite a while still to figure out that this little hole is indeed what the documentation calls a "button". Please add that you have to use a (thin) needle to push this "button". I wasn't sure and was a little afraid to maybe damage something inside...
Thanks!

**Comment by daringer** [comment]
valid point, added to the todos:
https://github.com/Nitrokey/nitrokey-documentation/issues/38
