### ISSUE TITLE
FIDO2: move reset and other details to subpages

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#40]
FIDO2: move reset and other details to subpages, leaving only an entry description on the main page, and asking to choose the topic from the left tree.
- File: [fido2/windows/index.rst] https://docs.nitrokey.com/fido2/windows/index

See https://github.com/Nitrokey/nitrokey-documentation/issues/24 for details.

**Comment by daringer** [comment]
fixed in current master
