### ISSUE TITLE
Feature: redirection on changed URL

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#41]
In case when the page's URL is changing, the docs system should remember the old one and redirect properly. The URLs are posted on the support forum and indexed, which makes the replies using the docs as the base unusable.

Example:
- https://support.nitrokey.com/t/windows-sign-in-with-fido2-standalone-pc/3115/2?u=szszszsz, a reply from 2 months ago, links to docs page which is not available anymore:
    - https://docs.nitrokey.com/pro/windows/login-with-eidauthenticate-on-stand-alone-windows-computers.html

**Comment by daringer** [comment]
no idea if this is even possible, changed the support-forum contents for now. 
Any idea how to realize this without spamming empty files into the documentation ?

**Comment by szszszsz** [comment]
Just a rough idea: I think tracking this by `uuid` number given to each document's header would be one of the solutions. Then on the docs generation references will update (by scanning all docs and extracting `uuid` and related file), and the old ones will be kept, and updated with the new path by the `uuid`.
Needs additional tooling probably (should be simple though).

**Comment by jans23** [comment]
That's not possible but tracked separately already.

**Comment by jans23** [comment]
We will define redirects manually, see README.
