### ISSUE TITLE
Storage 2: additional instructions for LUKS2 decryption using X509 certificate

### ISSUE THREAD

**Issue by VTimofeenko** [Nitrokey/nitrokey-documentation#43]
Hi!

I have written a [blog post](https://vtimofeenko.com/posts/unlocking-luks2-through-certificate-on-nitrokey-storage/) on how to:
* Configure X509 certificate on Nitrokey Storage using one of the existing PGP keys as private key for certificate
* Use that X509 certificate to unlock LUKS2 partition

I think it could be beneficial to add that link in [disk encryption doc](../tree/master/storage/linux/disk-encryption-luks.rst)

**Comment by jans23** [comment]
Cool. Will do. Thanks.
