### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-documentation#45]
File: [pro/linux/index.rst] https://docs.nitrokey.com/pro/linux/index.html

Following link mentioned on the site does not work:
- https://docs.nitrokey.com/pro/openpgp-email-encryption.html

**Comment by jans23** [comment]
@NitrokeyJakob FYA

**Comment by NitrokeyJakob** [comment]
already updated in latest Pull Request

**Comment by jans23** [comment]
This should be fixed. Please retest.

**Comment by szszszsz** [comment]
Confirmed. Closing as fixed.
Perhaps we could use some automatic link validation on the docs site?
