### ISSUE TITLE
headline "Tasten austauschen/löschen" → ¿"replace/delte keys"? → "Schlüssel  austauschen/löschen"

### ISSUE THREAD

**Issue by chri2** [Nitrokey/nitrokey-documentation#55]
File: [storage/linux/disk-encryption-luks.rst] https://docs.nitrokey.com/storage/linux/disk-encryption-luks

I guess you meant to translate 'keys'. In this context (and as correctly used in the paragraph below) 'keys' translates to 'Schlüssel'.

**Comment by daringer** [comment]
fixed in weblate
