### ISSUE TITLE
tweaks to improve Nitrophone documentation

### ISSUE THREAD

**Issue by mfc** [Nitrokey/nitrokey-documentation#62]
File: [nitrophone/index.rst](https://docs.nitrokey.com/nitrophone/index)

hey folks, I would modify the Nitrophone documentation to make it more in-line with Graphene OS suggestions, which also are simpler/clearer for users.

1. instead of suggesting user to install Shelter to create work profile dedicated for sandboxed google play services, just suggest the user creates a dedicated user profile:

https://grapheneos.org/usage#sandboxed-play-services

work profile is actually less secure than user profile:
https://www.reddit.com/r/GrapheneOS/comments/g0ly0j/comment/fnf2zra/?utm_source=share&utm_medium=web2x&context=3
["A work profile also works, although without as much isolation."](https://grapheneos.org/usage#sandboxed-play-services
)

2. Split APKs Installer (SAI) is available in F-Droid, so I would suggest the user downloads it from there rather than Aurora Store, to emphasize/make clear that it is a FOSS tool.

**Comment by daringer** [comment]
done in the latest documentation update, shall be available in some minutes...
