### ISSUE TITLE
dongleauth.com is outdated -> 2fa.directory

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-documentation#65]
File: [fido2/mac/index.rst] https://docs.nitrokey.com/fido2/mac/index

&

File: [fido2/windows/index.rst] https://docs.nitrokey.com/fido2/windows/index

see https://github.com/2factorauth/twofactorauth/issues/5238

Also your "Edit this Page | Request docs change" on https://docs.nitrokey.com/ is broken as you can see above

Edit: corrected link

**Comment by szszszsz** [comment]
The link on the main site, dongleauth.com, is for their Github repository and not for the previous domain name. So that's OK.
I do not understand fully what is your suggestion here. Can you elaborate?

**Comment by beerisgood** [comment]
dongleauth.com Is the old one (domain takeover) as you can read in the linked GitHub issue. 

2fa.directory Is the new domain which should be used.

**Comment by jans23** [comment]
It's the other way around: dongleauth.info is the old one, dongleauth.com is the new one maintained by us.

**Comment by beerisgood** [comment]
Oh yeah you’re right. Typo…

thanks @jans23 🍺

**Comment by beerisgood** [comment]
Looks like i drunk too much that day 😅
