### ISSUE TITLE
Please add the default user name in the faq

### ISSUE THREAD

**Issue by LaluSys** [Nitrokey/nitrokey-documentation#72]
File: [nitropc/faq.rst] https://docs.nitrokey.com/nitropc/faq

**Comment by jans23** [comment]
Only our Debian systems come with a default user name. Do you use Debian or do you refer to something else?

**Comment by LaluSys** [comment]
> Only our Debian systems come with a default user name. Do you use Debian or do you refer to something else?

I refer to Debian.

**Comment by jans23** [comment]
For Debian the configured user name is usually the customer's first name.

Because we don't offer Debian anymore, I don't think this is useful in the FAQ.
