### ISSUE TITLE
"Destroy encrypted data" was needed first time

### ISSUE THREAD

**Issue by tlikonen** [Nitrokey/nitrokey-documentation#81]
File: [storage/faq.rst] https://docs.nitrokey.com/storage/faq

In my brand new Nitrokey Storage 2 Nitrokey App's option "Unlock encrypted volume" didn't accept any PIN codes, not the one I had set nor the default 123456. I had to use "Destroy encrypted data" option first. It created new encryption keys or something. After that my PIN code was accepted by the "Unlock" option and I could create partition table, file system etc. for the encrypted volume.

The [FAQ](https://docs.nitrokey.com/storage/faq) documentation doesn't tell anything about destroying encrypted data. It should.

**Comment by daringer** [comment]
hey @tlikonen , thanks for the hint, added it to the FAQ as "Why can’t I access the encrypted storage on a new Nitrokey Storage?" https://docs.nitrokey.com/storage/faq.html
